/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 04-авг-2024 20:29:17 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS tests.tests CASCADE;

DROP TABLE IF EXISTS tests.answers CASCADE;

DROP TABLE IF EXISTS quizzes.quizzes CASCADE;

DROP TABLE IF EXISTS text_tasks.text_tasks CASCADE;


/* Create Tables */

CREATE TABLE tests.tests
(
    id uuid NOT NULL,
    content text NOT NULL,
    is_only_one_answer boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tests.tests ADD CONSTRAINT "PK_tests"
    PRIMARY KEY (id)
;

/* Create Tables */

CREATE TABLE text_tasks.text_tasks
(
    id uuid NOT NULL,
    content text NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE text_tasks.text_tasks ADD CONSTRAINT "PK_text_task"
    PRIMARY KEY (id)
;

/* Create Tables */

CREATE TABLE tests.answers
(
    id uuid NOT NULL,
    content text NOT NULL,
    is_correct boolean NOT NULL,
    test_id uuid NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tests.answers ADD CONSTRAINT "PK_answers"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_answers_tests" ON tests.answers (test_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE tests.answers ADD CONSTRAINT "FK_answers_tests"
    FOREIGN KEY (test_id) REFERENCES tests.tests (id) ON DELETE Cascade ON UPDATE Cascade
;

/* Create Tables */

CREATE TABLE quizzes.quizzes
(
    id uuid NOT NULL,
    content text NOT NULL,
    answer text NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE quizzes.quizzes ADD CONSTRAINT "PK_quizzes"
    PRIMARY KEY (id)
;
