/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 06-СЏРЅРІ-2024 18:10:25 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS tests.tests CASCADE
;

/* Create Tables */

CREATE TABLE tests.tests
(
    id uuid NOT NULL,
    content text NOT NULL,
    is_only_one_answer boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tests.tests ADD CONSTRAINT "PK_tests"
    PRIMARY KEY (id)
;
