/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 06-СЏРЅРІ-2024 18:11:23 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS tests.answersDto CASCADE
;

/* Create Tables */

CREATE TABLE tests.answers
(
    id uuid NOT NULL,
    content text NOT NULL,
    is_correct boolean NOT NULL,
    test_id uuid NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE tests.answers ADD CONSTRAINT "PK_answers"
    PRIMARY KEY (id)
;

CREATE INDEX "IXFK_answers_tests" ON tests.answers (test_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE tests.answers ADD CONSTRAINT "FK_answers_tests"
    FOREIGN KEY (test_id) REFERENCES tests.tests (id) ON DELETE Cascade ON UPDATE Cascade
;
