/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 03-авг-2024 15:23:39 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS quizzes.quizzes CASCADE
;

/* Create Tables */

CREATE TABLE quizzes.quizzes
(
    id uuid NOT NULL,
    content text NOT NULL,
    answer text NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE quizzes.quizzes ADD CONSTRAINT "PK_quizzes"
    PRIMARY KEY (id)
;
