version: "3.2"
services:
  pg-db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  tasks-service:
    image: usachev/tasks-service
    container_name: tasks-service
    ports:
      - "8080:8080"
